@startuml
skinparam defaultFontName "Times New Roman"
skinparam defaultFontSize 12 
skinparam defaultFontColor black

participant DartApp
participant VideoMain
'participant VideoFrameThread

par VideoMain Thread
    activate VideoMain
    VideoMain -> VideoMain: Socket belegen

    loop wait for connection
        VideoMain -> VideoMain: auf Socket lauschen
    end

    VideoMain -> : Kamera Verbindung öffnen
    VideoMain -> : Thread für Frames erstellen
    'VideoMain -> VideoFrameThread: create
    deactivate VideoMain

else DartApp Thread
    activate DartApp

    loop connecting
        DartApp -> VideoMain: Verbinden
    end

    DartApp -> DartApp: Spiel Start
    deactivate DartApp
end
@enduml