@startuml
skinparam defaultFontName "Times New Roman"
skinparam defaultFontSize 12 
skinparam defaultFontColor black

participant DartApp
participant VideoMain
'participant VideoFrameThread

par VideoMain Thread
    activate VideoMain
    VideoMain -> VideoMain: bindSocket

    loop waiting for connection
        VideoMain -> VideoMain: listen
    end

    VideoMain -> : openCameraConnection
    VideoMain -> : createFrameThread
    'VideoMain -> VideoFrameThread: create
    deactivate VideoMain

else DartApp Thread
    activate DartApp

    loop connecting
        DartApp -> VideoMain: connect
    end

    DartApp -> DartApp: Gamestart
    deactivate DartApp
end
@enduml