@startuml
skinparam defaultFontName "Times New Roman"
skinparam defaultFontSize 12 
skinparam defaultFontColor black

participant DartApp
participant VideoMain
participant FileSystem
participant Server

loop player playing Dart

    loop not game ended
        activate DartApp
        DartApp -> VideoMain: sendHit
        deactivate DartApp
        activate VideoMain

        VideoMain -> FileSystem: saveraw
        activate FileSystem

        FileSystem -> FileSystem: save
        deactivate FileSystem

        deactivate VideoMain
    end
    
    DartApp -> DartApp: gamefinished
    activate DartApp

    DartApp -> VideoMain: sendgamefinished    
    deactivate DartApp
    activate VideoMain

    VideoMain -> FileSystem: readraw
    activate FileSystem

    FileSystem --> VideoMain: data
    deactivate FileSystem

    VideoMain -> VideoMain: compressvideo

    VideoMain -> FileSystem: savecompressed
    activate FileSystem

    FileSystem -> FileSystem: save
    deactivate FileSystem

    VideoMain -> DartApp: sendvideofinished(path)
    deactivate VideoMain
    activate DartApp

    DartApp -> FileSystem: getVideo
    deactivate DartApp
    activate FileSystem

    FileSystem -> DartApp: video
    deactivate FileSystem
    activate DartApp

    DartApp -> Server: uploadvideo
    deactivate DartApp
    activate Server
end
@enduml