@startuml
skinparam defaultFontName "Times New Roman"
skinparam defaultFontSize 12 
skinparam defaultFontColor black

participant VideoFramesThread
participant Kamera

-> VideoFramesThread: Erstellen
activate VideoFramesThread

loop reading frames
    VideoFramesThread -> Kamera: Frames anfragen
    deactivate VideoFramesThread
    activate Kamera
    Kamera -> VideoFramesThread: Frame übertragen
    deactivate Kamera
    activate VideoFramesThread

    VideoFramesThread -> VideoFramesThread: Frames in Ringbuffer schreiben
    deactivate VideoFramesThread
end
@enduml