@startuml
skinparam defaultFontName "Times New Roman"
skinparam defaultFontSize 12 
skinparam defaultFontColor black

participant DartApp
participant VideoMain
participant FileSystem
participant Server

loop player playing Dart

    loop not game ended
        activate DartApp
        DartApp -> VideoMain: treffer senden
        deactivate DartApp
        activate VideoMain

        VideoMain -> FileSystem: Rohdaten speichern
        activate FileSystem

        FileSystem -> FileSystem: speichern
        deactivate FileSystem

        deactivate VideoMain
    end
    
    DartApp -> DartApp: Spiel Ende
    activate DartApp

    DartApp -> VideoMain: Spiel Ende senden    
    deactivate DartApp
    activate VideoMain

    VideoMain -> FileSystem: Rohdaten lesen
    activate FileSystem

    FileSystem --> VideoMain: Daten
    deactivate FileSystem

    VideoMain -> VideoMain: Video komprimieren

    VideoMain -> FileSystem: Video speichern
    activate FileSystem

    FileSystem -> FileSystem: speichern
    deactivate FileSystem

    VideoMain -> DartApp: 'Video fertig' senden
    deactivate VideoMain
    activate DartApp

    DartApp -> FileSystem: Video Datei lesen
    deactivate DartApp
    activate FileSystem

    FileSystem -> DartApp: Video
    deactivate FileSystem
    activate DartApp

    DartApp -> Server: Video hochladen
    deactivate DartApp
    activate Server
end
@enduml