@startuml
skinparam defaultFontName "Times New Roman"
skinparam defaultFontSize 12 
skinparam defaultFontColor black

participant Video-Frames-Thread
participant Kamera

-> Video-Frames-Thread: create()
activate Video-Frames-Thread

loop reading frames
    Video-Frames-Thread -> Kamera: receive-frame()
    deactivate Video-Frames-Thread
    activate Kamera
    Kamera -> Video-Frames-Thread: deliver frame
    deactivate Kamera
    activate Video-Frames-Thread

    Video-Frames-Thread -> Video-Frames-Thread: buffer-frames
    deactivate Video-Frames-Thread
end
@enduml