@startuml
skinparam defaultFontName "Times New Roman"
skinparam defaultFontSize 12 
skinparam defaultFontColor black

participant Dart-App
participant Video-Main
'participant Video-Frame-Thread

par Video-Main Thread
    Video-Main -> Video-Main: bind-Socket
    activate Video-Main
    deactivate Video-Main

    loop waiting for connection
        Video-Main -> Video-Main: listen
    end

    Video-Main -> : open-Camera-Connection
    Video-Main -> : create-Frame-Thread
    'Video-Main -> Video-Frame-Thread: create

else Dart-App Thread
    loop connecting
        Dart-App -> Video-Main: connect
    end

    Dart-App -> Dart-App: Game-start
end
@enduml