@startuml
skinparam defaultFontName "Times New Roman"
skinparam defaultFontSize 12 
skinparam defaultFontColor black

participant VideoFramesThread
participant Kamera

-> VideoFramesThread: create()
activate VideoFramesThread

loop reading frames
    VideoFramesThread -> Kamera: receiveframe()
    deactivate VideoFramesThread
    activate Kamera
    Kamera -> VideoFramesThread: deliver frame
    deactivate Kamera
    activate VideoFramesThread

    VideoFramesThread -> VideoFramesThread: bufferframes
    deactivate VideoFramesThread
end
@enduml