@startwbs

skinparam defaultFontName "Times New Roman"
skinparam defaultFontSize 12 
skinparam defaultFontColor black

* Video-Api /video
** /{playerId}/{filename}
*** GET
*** POST
** /videos
*** GET

@endwbs