@startuml
skinparam defaultFontName "Arial"
skinparam defaultFontSize 12 
skinparam defaultFontColor black

participant Sender
participant Receiver

activate Sender
Sender -> Sender: Daten serialisieren
Sender -> Receiver: Daten Länge senden

activate Receiver
Receiver -> Receiver: Länge lesen
Sender -> Receiver: Daten senden
deactivate Sender

Receiver -> Receiver: Daten anhand der länge lesen
Receiver -> Receiver: Daten deserialisieren
deactivate Receiver

@enduml